version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
    - build
jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: scripts/install-dependencies.sh
      - run:
          name: Place example data sets in the home directory
          command: cp -r example-data-sets/* ~/
      - run:
          name: Run benchmark
          command: |
            export POSTGRES_INPUT_DATA_DIR=~/graphs
            scripts/package-and-run-benchmark.sh
      - slack/status
