version: 2.1
orbs:
  slack: circleci/slack@3.4.2
workflows:
  version: 2
  build:
    jobs:
    - build
jobs:
  build:
    docker:
      - image: cimg/base:2023.02-22.04
    resource_class: xlarge
    steps:
      - checkout
      - run: scripts/install-dependencies.sh
      - run: cp -r example-data-sets/graphs ~/
      - run: |
          export POSTGRES_INPUT_DATA_DIR=~/graphs
          bin/scripts/start-postgres.sh
          scripts/package-and-run-benchmark.sh
